### ISSUE TITLE
Span of  footer icon links 

### ISSUE THREAD

**Issue by harishnandan** [kossiitkgp/kwoc-2017#49]
![img_20171107_120441](https://user-images.githubusercontent.com/24224542/32480529-2b900a92-c387-11e7-89a7-a90095722136.jpg)

Should the span of the links be kept same or be decreased?
@pranitbauva1997 @djbarnwal @nitinkgp23

**Comment by OrkoHunter** [comment]
I think the larger span has a design benefit as it engages user attention for clicks due to its cursor.
