### ISSUE TITLE
Manuals are incorrectly linked.

### ISSUE THREAD

**Issue by harishnandan** [kossiitkgp/kwoc-2017#63]
The Student's / Mentor's manual leads to localhost/faq which does not exist.

**Comment by dibyadas** [comment]
This will be fixed as soon as @sangeet259 's [PR](https://github.com/kossiitkgp/kwoc-2017/pull/59) is merged after making a few changes.

**Comment by harishnandan** [comment]
Ohh i didn't see that. @sangeet259 Can you please reference this issue in your PR.

**Comment by sangeet259** [comment]
@harishnandan @dibyadas 
Yeah Sure, I had fixed this but a force push reverted it. I am sending a PR soon cherry picking all those commits. Hang On!

**Comment by sangeet259** [comment]
@harishnandan  You may close this!
